---
- hosts: localhost
  become: yes

  vars_prompt:

   - name: "new_user"
     prompt: "Account need to be create in remote server."
     private: no

  tasks:
    - name: creating the user {{ new_user }}.
      user:
        name: "{{ new_user }}"
        createhome: yes
        shell: /bin/bash
        append: yes
        state: present  

    - name: Create a dedicated sudo entry file for the user.
      file:
        path: "/etc/sudoers.d/{{ new_user }}"
        state: touch
        mode: '0600'

    - name: "Setting up Sudo without Password for user {{ new_user }}."
      lineinfile:
        dest: "/etc/sudoers.d/{{ new_user }}"
        line: '{{ new_user }}  ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: SSH KeyGen command
      tags: run
      shell: > 
        ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/kubeadmin_id_rsa
        creates="~/.ssh/kubeadmin_id_rsa"

    - name: add the public key into Authorized_keys file to enable Key Auth
      shell: "cat ~/.ssh/kubeadmin_id_rsa.pub >> ~/.ssh/authorized_keys"
      register: addtoauth
    - name: Fetch the keyfile from the node to master
      tags: run
      fetch: 
        src: "~/.ssh/kubeadmin_id_rsa"
        dest: "/home/ubuntu/playbook/kubeadmin_id_rsa.pem"
        flat: yes
    - name: Print the created user.
      shell: id "{{ new_user }}"
      register: new_user_created

    - debug:
        msg: "{{ new_user_created.stdout_lines[0] }}"
...
